spring.application.name=api-monitoring-dashboard
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

monitoring.alert.slow-threshold=500
monitoring.alert.high-threshold=1000
monitoring.alert.critical-threshold=2000
